apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  namespace: default
data:
  # Database
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "go_practice"
  
  # OIDC (public config)
  OIDC_ISSUER_URL: "https://accounts.google.com"
  OIDC_AUTH_URL: "https://accounts.google.com/o/oauth2/v2/auth"
  OIDC_TOKEN_URL: "https://oauth2.googleapis.com/token"
  OIDC_USERINFO_URL: "https://openidconnect.googleapis.com/v1/userinfo"
  OIDC_ISSUER: "https://accounts.google.com"
  OIDC_REDIRECT_URL: "https://api.example.com/auth/callback"
  OIDC_POST_LOGOUT_URL: "https://app.example.com"
  
  # App config
  PORT: "8080"
  LOG_LEVEL: "info"
  MODE: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: go-api-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  DB_USER: b2lkY19hcGlfdXNlcg==  # oidc_api_user
  DB_PASSWORD: b2lkY19zZWN1cmVfcGFzc3dvcmRfMjAyNQ==  # oidc_secure_password_2025
  OIDC_CLIENT_ID: OTA2ODA4NjI5NDQ1LWlha3A1aWxma2M5bHRtbms1ajNvMDAxZHZ2cmVzMHRuLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t  # real Google Client ID
  OIDC_CLIENT_SECRET: R09DU1BYLU1iQVpvbVVtUjFqMkV3dXhmZEIyVE9xU1NVcVI=  # real Google Client Secret
  JWT_SIGNING_KEY: ZGV2LWp3dC1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # dev-jwt-secret-key-change-in-production
  SESSION_SECRET: ZGV2LXNlc3Npb24tc2VjcmV0LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # dev-session-secret-change-in-production
