apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  labels:
    app: go-api
    component: migration
spec:
  backoffLimit: 3
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: go-api
        component: migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migration
          image: nabuhotnii/go-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running database migrations..."
              echo "Creating configuration..."
              /root/api-server configure -o /tmp/_local.hcl -m production
              echo "Running migrations..."
              /root/api-server migrate -c /tmp/_local.hcl
          envFrom:
            - configMapRef:
                name: go-api-config
            - secretRef:
                name: go-api-secrets
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
