apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: 2025-08-02T19:50:52Z
      labels:
        app: go-api
    spec:
      initContainers:
        - name: db-migration
          image: nabuhotnii/go-api:75290d8445b6390b578e1175cc43c9d7b10a3d3f
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Running database migrations..."
              cat > /tmp/migration.hcl << 'EOF'
              server {
                host = "0.0.0.0"
                port = 8080
                environment = "production"
                log_level = "info"
                log_format = "text"
                read_timeout = "30s"
                write_timeout = "30s"
                idle_timeout = "120s"
              }
              
              database {
                driver = "postgres"
                host = "postgres-service"
                port = 5432
                name = "go_practice"
                user = "oidc_api_user"
                password = "oidc_secure_password_2025"
                ssl_mode = "disable"
                max_open_connections = 10
                max_idle_connections = 5
                connection_max_lifetime = "5m"
              }
              
              oidc {
                provider {
                  issuer_url = "https://accounts.google.com"
                  client_id = "dummy"
                  client_secret = "dummy"
                  redirect_url = "https://api.example.com/auth/callback"
                  post_logout_redirect_url = "https://app.example.com"
                  auth_url = "https://accounts.google.com/o/oauth2/v2/auth"
                  token_url = "https://oauth2.googleapis.com/token"
                  userinfo_url = "https://openidconnect.googleapis.com/v1/userinfo"
                  issuer = "https://accounts.google.com"
                }
                
                tokens {
                  signing_key = "dev-jwt-secret"
                  signing_method = "HS256"
                  access_token_duration = "1h"
                  refresh_token_duration = "24h"
                  id_token_duration = "1h"
                }
                
                scopes = ["openid", "profile", "email"]
              }
              
              security {
                cors {
                  allowed_origins = ["*"]
                  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
                  allowed_headers = ["*"]
                  allow_credentials = true
                  max_age = 3600
                }
                
                rate_limit {
                  enabled = true
                  requests_per_minute = 100
                  burst = 50
                }
                
                session {
                  secret = "dev-session-secret"
                  max_age = 3600
                  secure = false
                  http_only = true
                }
              }
              
              redis {
                enabled = false
                host = "localhost"
                port = 6379
                password = ""
                database = 0
                max_retries = 3
                pool_size = 10
              }
              EOF
              
              /root/api-server migrate -c /tmp/migration.hcl
          envFrom:
            - configMapRef:
                name: go-api-config
            - secretRef:
                name: go-api-secrets
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
      containers:
        - name: go-api
          image: nabuhotnii/go-api:75290d8445b6390b578e1175cc43c9d7b10a3d3f
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: go-api-config
            - secretRef:
                name: go-api-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
