name: Build and Push Go API Docker Image

on:
  push:
    branches:
      - master  # Виконується при пуші в гілку master

permissions:
  contents: write  # Дозволяє push змін

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t nabuhotnii/go-api:${{ github.sha }} -t nabuhotnii/go-api:latest -f ./Dockerfile .

    - name: Push Docker image
      run: |
        docker push nabuhotnii/go-api:${{ github.sha }}
        docker push nabuhotnii/go-api:latest

    # Не змінюємо файли - без конфліктів!
    - name: Success message
      run: |
        echo "✅ Go API Docker images pushed successfully!"
        echo "📦 Image: nabuhotnii/go-api:${{ github.sha }}"
        echo "🔄 ArgoCD will detect changes automatically"


